# Esse Workflow é responsável pela execução dos testes unitários da biblioteca.
name: Tests with pytest

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'

jobs:
  test:
    strategy:
      matrix:
        python: ["3.10", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to source branch
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies and prepare environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          python -m pip install -e .[all]


      - name: Run tests with pytest
        run: pytest
